"""comment

Revision ID: 7d80a49dcee8
Revises: 9eccda887fd0
Create Date: 2021-10-25 20:43:50.758850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d80a49dcee8'
down_revision = '9eccda887fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
