"""comment

Revision ID: 9eccda887fd0
Revises: b2eaca49337e
Create Date: 2021-10-25 20:42:39.462803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eccda887fd0'
down_revision = 'b2eaca49337e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
